### ISSUE TITLE
The tutorial samples did not work for me

### ISSUE THREAD

**Issue by cshuxteau** [scverse/spatialdata-notebooks#31]
I tried python 3.10 and python 3.11, I got the same issue when running the Transformation and Coordinate sample notebook.   I could not get neither the scale nor the transformation example to render as displayed in the tutorial.  I got the identical warning messages. But my output did not change from the previous step, there was no scaling nor transformation.  

![error1](https://github.com/scverse/spatialdata-notebooks/assets/119473013/7188d8b4-f1dd-47a1-9546-5153fc3dd352)

However, If I modify the code to the following:

scale = Scale([0.5], axes=("x",))
set_transformation(sdata.images["raccoon"], scale, to_coordinate_system="global")
sdata.pl.render_labels().pl.render_shapes().pl.render_images().pl.show()

By changing the scale value to be 0.5, I did see the scale transformation, but it applies to all elements, not just the image. 

![image](https://github.com/scverse/spatialdata-notebooks/assets/119473013/5aa5b22b-3d82-48b8-b70d-255e9fb895cb)

Please advise.  Thank you!

**Comment by duxiuju** [comment]
I've got the same issue as you decscribed and wait for solution

**Comment by LucaMarconato** [comment]
@duxiuju @cshuxteau sorry I missed this notification and saw the issue just now. Thanks for reporting, I will look into this and get back to this in the next days. 

CC @timtreis, do we have tests for plots equivalent to this in the `spatialdata-plot` repo?

**Comment by LucaMarconato** [comment]
@timtreis perfect thanks a lot!

**Comment by LucaMarconato** [comment]
It should be fixed (since quite some releases) now.
