### ISSUE TITLE
Multiple spatialdata objects in napari not supported

### ISSUE THREAD

**Issue by melonora** [scverse/spatialdata-notebooks#38]
In 00_xenium_and_visium the following code section requires multiple spatialdata objects to be supported. This is not yet the case in the main branch of `napari-spatialdata`.
```
# we can visualize the results with napari
from napari_spatialdata import Interactive

Interactive([xenium_subset, landmarks_sdata])
```

**Comment by LucaMarconato** [comment]
Issue to keep track of the multiple sdata in napari issue: https://github.com/scverse/napari-spatialdata/issues/112
